### ISSUE TITLE
Settings menu bugged

### ISSUE THREAD

**Issue by DaveyLovesCode** [ryngonzalez/ChatGPT-for-Mac#2] opened 2023-03-14 16:57 UTC
Amazing initial release!!

When right clicking to change the global hot key, it opens a window chatGPT for Mac Settings, however it just displays the icon very large. There's no settings:
![Screenshot 2023-03-14 at 11 56 47 AM](https://user-images.githubusercontent.com/53842399/225080400-a451ef08-badc-4cc9-952d-2a5f305531b4.png)
Thanks for releasing this!

**Comment by ryngonzalez** [comment] 2023-03-14 20:16
Hey thanks for submitting @DaveyUS! Please let me know if this latest release fixes your issue: 

https://github.com/ryngonzalez/ChatGPT-for-Mac/releases/tag/1.0.1

**Comment by DaveyLovesCode** [comment] 2023-03-14 20:25
I can now see and set the settings, however the image is still there as a background which looks weird.

![Screenshot 2023-03-14 at 3 22 49 PM](https://user-images.githubusercontent.com/53842399/225127563-77020e08-17c2-4acc-b27b-f006617a6930.png)

Also just to avoid creating another issue, it would be great if we could hit the enter key to submit a chat message. Currently hitting enter creates a line break which generally is accomplished with Shift+Enter.

Thanks for being such a quick dev!

**Comment by ryngonzalez** [comment] 2023-03-14 20:35
What version of macOS are you on btw? I'm currently unable to reproduce on 13.2.1, so trying to narrow down the issue.

**Comment by DaveyLovesCode** [comment] 2023-03-14 20:40
I'm on 13.2.1 with an M2.

Sorry for piling on small things, but it would also be great if the typing prompt would automatically be focused and ready for input every time I re-open it with the global hotkey. 

If this app ends up replacing macGPT for me, I'll donate!

**Comment by DaveyLovesCode** [comment] 2023-03-14 20:41
Let me know if you need me to run any tests or anything.

**Comment by ryngonzalez** [comment] 2023-03-14 21:54
No worries, love the feedback! I'll investigate.

**Comment by ryngonzalez** [comment] 2023-03-14 22:08
@DaveyUS please check out this updated release with a new cut of the app; I think this _may_ fix the settings issue, but does add the enter key to submit feature!

**Comment by DaveyLovesCode** [comment] 2023-03-14 23:03
Unfortunately, the settings issue still remains but it's not a deal breaker for me. The enter key addition is perfect!! Where can I donate?

**Comment by ryngonzalez** [comment] 2023-03-20 03:03
Fixed in https://github.com/ryngonzalez/ChatGPT-for-Mac/releases/tag/1.0.2

**Closed as completed by ryngonzalez** 2023-03-20 03:03 UTC
